### ISSUE TITLE
f_dwepdcunitread_epd is not defined

### ISSUE THREAD

**Issue by mighty1231** [armoha/euddraft#10]
**description**
Although I wrote `from eudplib import *` on the top of the code, `NameError` is raised.
`f_dwepdcunitread_epd` is not defined.

**screenshot**
![image](https://user-images.githubusercontent.com/10972723/82024028-1e0dc300-96ca-11ea-99dd-ff866fc459d3.png)

**Comment by armoha** [comment]
Right name is `f_cunitepdread_epd`.

Usage:
```py
ptr, epd = f_cunitepdread_epd(EPD(NEXT_UNIT_PTR));
```

Examples:
  https://cafe.naver.com/edac/83176
  https://cafe.naver.com/edac/83365
