### ISSUE TITLE
I cann't compile since euddraft 0.9.9.0

### ISSUE THREAD

**Issue by boermyth** [armoha/euddraft#14]
It will display：

Build failed. Please check the log for details.
[Error] Array length must be >= 0, not -1 Traceback (most recent call last):
  File "C:\Py\lib\ctypes\__init__.py", line 62, in create_string_buffer
ValueError: Array length must be >= 0, not -1
==============

Even though, I just use eud‘s protect without any eud, it cann't compile at the same. But i cann't find which array's length is -1. So I am puzzled all the time. I want to know how to deal with this problem.

Thank you for your good job.

**Comment by armoha** [comment]
Hi, have you tried using latest release?

**Comment by boermyth** [comment]
Yes，i have tried euddraft 0.9.9.7, but it is the same.

**Comment by boermyth** [comment]
> Hi, have you tried using latest release?

Yes，i have tried euddraft 0.9.9.7, but it is the same.

**Comment by armoha** [comment]
Can you send me a basemap if the problem only occurs in specific maps? Thank you.

**Comment by boermyth** [comment]
how can i send you, what is your e-mail?

**Comment by armoha** [comment]
kein0011{at}naver<dot>com

**Comment by armoha** [comment]
`(listfile)` in mpq contains 'Mgr' and 'Cmd' which are not actual files.
They have filesize of -1, not a valid file. Anyways thanks for reporting, fixed!
https://github.com/armoha/euddraft/releases/tag/v0.9.0.8

**Comment by boermyth** [comment]
> `(listfile)` in mpq contains 'Mgr' and 'Cmd' which are not actual files.
> They have filesize of -1, not a valid file. Anyways thanks for reporting, fixed!
> https://github.com/armoha/euddraft/releases/tag/v0.9.0.8

Thank you so much, I remember the ' Mgr' and 'Cmd' which belong SC1.08b eud of a sudden, and in the past i removed them. Thank you for your help.
