### ISSUE TITLE
How to use FadeIn/FadeOut ?

### ISSUE THREAD

**Issue by gxz567** [armoha/euddraft#15]
What does the "tecolor" mean in this function(in CHANGELOG_ko.md)?

function texteffect() {
    const **tecolor** = 4, 2, 0x1E, 5, 0;
    const t = s.fadeIn("\x13\x04세상은 \x19하나의 빛\x04으로부터 창조되었다.
\n \n\x13\x04빛은 공허를 두개로 갈라 하늘과 땅을 만들었고
\n\x13\x04그곳을 자신의 이름을 따 \x19아티아월드\x04라고 이름지었다.",
        line=6, color=tecolor, wait=2, tag=py_str("FAH")

**Comment by armoha** [comment]
Text effect colors xD
Have you already used text color code in SCMDraft2 or other SC related tools?
http://www.staredit.net/wiki/index.php/Color#Menu_formatting

`4, 2, 0x1E, 5, 0` means that the color of each character will be changed from original color to `white, light blue, blue gray, gray and invisible`.

In `fadeIn`, text effects will move from left to right. In `fadeOut` the transition is from right to left.

**Comment by armoha** [comment]
Simple visualization example>

```js
const s = StringBuffer();
const text_colors = 0x02, 0x05, 0x00;  // light blue -> gray -> invisible
s.fadeIn(SCMD2Text("<04>What does <07>`tecolor` mean?"), color=text_colors);
```

0) No text is shown (texts after `\0` are removed)
```
<00>
```

1) `W` in gray
```
<05>W<00>
```

2) `W` in light blue, `h` in gray
```
<02>W<05>h<00>
```

3) `W` in white(original color), `h` in light blue, `a` in gray
```
<04>W<02>h<05>a<00>
```

4) `Wh` in white, `a` in light blue, `t` in gray

```
<04>Wh<02>a<05>t<00>
```

So texts appears gradually from left to right.

**Comment by gxz567** [comment]
Thx for answering lol
I tried to run these codes below(from your changelog_ko.md@0.8.6.0),but only see white(0x04) texts on the line 6 all the time,without any change.
`const s = StringBuffer(1023);`
`function texteffect() {`
`const tecolor = 0x07, 0x03, 0x08;`
`const t = s.fadeIn("\x13\x04sounds interesting",line=6, color=tecolor, wait=2, tag=py_str("FAH") );`
`if(t >= 1) return;`
`var wait;`
`wait += 1;`
`if(wait <= 99) return;`
`wait = 0;`
`TextFX_SetTimer("FAH", SetTo, 0);`
`TextFX_Remove("FAH");`
`}`
`function afterTriggerExec() {`
`    foreach(h : EUDLoopPlayer()) {`
`        setcurpl(h);`
`        texteffect();`
`    }`
`}
I also tried the code you've just reply me,didn't see any change :(

In the map "ZombieHunter Ⅱ",I see the text effect tat the beginning.
How to work it out?

By the way,here is one of my map called Raiden Fighter xD.
WASD move,auto attack,JN special weapon,KL bomb,I invincible,M bomb change MP :)
[Raiden Fighters V1.38.zip](https://github.com/armoha/euddraft/files/5719349/Raiden.Fighters.V1.38.zip)

**Comment by armoha** [comment]
Did you turn on EUDTurbo?

**Comment by gxz567** [comment]
> Did you turn on EUDTurbo?

Sorry,I changed  #EUDTurbo.
The code `SetMemory(0x6509A0, SetTo, 0);` changed to `SetMemory(0x6509A0, SetTo,  1);` so as to increase the game speed.
Thx xD

**Comment by armoha** [comment]
Going to close this as resolved but feel free to ask question.
