### ISSUE TITLE
[epScript] Bug on modifying current upgrade level

### ISSUE THREAD

**Issue by armoha** [armoha/euddraft#151]
![image-12](https://github.com/user-attachments/assets/11afdae7-be0b-4cca-90c6-0728756d6a6e)
```js
  once(t.time >= 3) {
      const upg = Upgrade("Protoss Ground Weapons");
      upg[P1] = 1;
      simpleprint("111111");
  } 
```
> **GGRush**: Hi Armo, nothing happens
> Unable to write

**Comment by GGrush-Doudizhu** [comment]
bug: Upgrade("Protoss Ground Weapons")[player]
need to add parenthese: (Upgrade("Protoss Ground Weapons"))[player]
Is this a problem?Is there a problem with the order of operations?

**Comment by GGrush-Doudizhu** [comment]
also:
if we have a function func() return a, b
bug: func()[0] or func()[1]
when I write (func())[0], correct

**Comment by GGrush-Doudizhu** [comment]
also:
const x = a + b << c;
euddraft will calculate a+b first, and then (a+b)<<c
when I write a+ (b<<c) , correct
It seems that euddraft did not prioritize shift operations over addition and subtraction operations

**Comment by armoha** [comment]
> bug: Upgrade("Protoss Ground Weapons")[player] need to add parenthese: (Upgrade("Protoss Ground Weapons"))[player] Is this a problem?Is there a problem with the order of operations?

There's ambiguous syntax in epScript between return value selection and array literal. See https://github.com/armoha/euddraft/issues/114

> also: const x = a + b << c; euddraft will calculate a+b first, and then (a+b)<<c when I write a+ (b<<c) , correct It seems that euddraft did not prioritize shift operations over addition and subtraction operations

It follows the bad tradition of C language. For now, always use parentheses if you think it is confusing. See https://www.foonathan.net/2017/07/operator-precedence/ for details on this topic:
> The C programming language - and thus many derived languages - has a great example of “bad precedence” that annoys me anytime I use it. The precedence of the binary bitwise operators (&, |, …) is lower than that of the comparison operators (== or ‘<`).

**Comment by armoha** [comment]
Unable to reproduce in development version, maybe already fixed issue.
![Screenshot_20241228_123930_Moonlight](https://github.com/user-attachments/assets/d99dc55a-5dd4-4a2b-8fb6-1ade794e1057)

**Comment by armoha** [comment]
This issue only happens in epScript code due to`_ARRW`
