### ISSUE TITLE
Can't install eudplib in macOS

### ISSUE THREAD

**Issue by zuhanit** [armoha/euddraft#152]
<details>
<summary>System Info</summary>

<!DOCTYPE html>
Item | Value
-- | --
CPUs | Apple M4
Memory (System) | 2GB(14GB free)
OS | macOS 15.1.1
Python Version | 3.11.10 64-bit, using UV as virtual environment
rustc Version | 1.82.0
</details>

<details>
<summary>Error Log</summary>

<!DOCTYPE html>
(backend) ➜  backend git:(master) ✗ uv add eudplib
Resolved 11 packages in 205ms
  × Failed to download and build `eudplib==0.79.6`
  ╰─▶ Build backend failed to build wheel through `build_wheel` (exit status: 1)

      [stdout]
      Running `maturin pep517 build-wheel -i /Users/hamjoohan/.cache/uv/builds-v0/.tmpLZCDEj/bin/python --compatibility off`

      [stderr]
      📦 Including license file "/Users/hamjoohan/.cache/uv/sdists-v6/pypi/eudplib/0.79.6/0WPBrRkCoGPnt-WB95-5-/src/LICENSE"
      🍹 Building a mixed python/rust project
      🔗 Found pyo3 bindings with abi3 support for Python ≥ 3.10
      🐍 Not using a specific python interpreter
      📡 Using build options features, locked from pyproject.toml
      💻 Using `MACOSX_DEPLOYMENT_TARGET=11.0` for aarch64-apple-darwin by default
         Compiling pyo3-build-config v0.22.3
         Compiling pyo3-ffi v0.22.3
         Compiling pyo3-macros-backend v0.22.3
         Compiling pyo3 v0.22.3
         Compiling pyo3-macros v0.22.3
         Compiling eudplib-epscript v0.1.0
      (/Users/hamjoohan/.cache/uv/sdists-v6/pypi/eudplib/0.79.6/0WPBrRkCoGPnt-WB95-5-/src/src/rust/eudplib-epscript)
         Compiling eudplib-stormlib v0.1.0
      (/Users/hamjoohan/.cache/uv/sdists-v6/pypi/eudplib/0.79.6/0WPBrRkCoGPnt-WB95-5-/src/src/rust/eudplib-stormlib)
      error[E0425]: cannot find value `cfile_path` in this scope
         --> eudplib-stormlib/src/lib.rs:146:13
          |
      146 |             cfile_path.as_ptr(),
          |             ^^^^^^^^^^ help: a local variable with a similar name exists: `file_path`

      For more information about this error, try `rustc --explain E0425`.
      error: could not compile `eudplib-stormlib` (lib) due to 1 previous error
      warning: build failed, waiting for other jobs to finish...
      💥 maturin failed
        Caused by: Failed to build a native library through cargo
        Caused by: Cargo build finished with "exit status: 101": `env -u CARGO MACOSX_DEPLOYMENT_TARGET="11.0"
      PYO3_ENVIRONMENT_SIGNATURE="cpython-3.11-64bit" PYO3_PYTHON="/Users/hamjoohan/.cache/uv/builds-v0/.tmpLZCDEj/bin/python"
      PYTHON_SYS_EXECUTABLE="/Users/hamjoohan/.cache/uv/builds-v0/.tmpLZCDEj/bin/python" "cargo" "rustc"
      "--features" "pyo3/abi3-py310" "--message-format" "json-render-diagnostics" "--locked" "--manifest-path"
      "/Users/hamjoohan/.cache/uv/sdists-v6/pypi/eudplib/0.79.6/0WPBrRkCoGPnt-WB95-5-/src/src/rust/Cargo.toml" "--release" "--lib" "--"
      "-C" "link-arg=-undefined" "-C" "link-arg=dynamic_lookup" "-C" "link-args=-Wl,-install_name,@rpath/eudplib.bindings._rust.abi3.so"`
      Error: command ['maturin', 'pep517', 'build-wheel', '-i', '/Users/hamjoohan/.cache/uv/builds-v0/.tmpLZCDEj/bin/python',
      '--compatibility', 'off'] returned non-zero exit status 1

  help: `eudplib` (v0.79.6) was included because `backend` (v0.1.0) depends on `eudplib`
</details>

Installing eudplib was failed while using `uv add eudplib` or `uv pip install eudplib` on macOS. I've installed stormilb manually, anyway error exists.

**Comment by armoha** [comment]
https://github.com/armoha/eudplib/blob/c3353eabc2bd431c9004bd3737e8d7a48fcc60dd/src/rust/eudplib-stormlib/src/lib.rs#L124 is a culprit and should be renamed to `cfile_path` to match the name.

**Comment by zuhanit** [comment]
@armoha Renamed `cpath` to `cfile_path` and build eudplib was successful. Thanks!

**Comment by zuhanit** [comment]
Anyway, I can't build euddraft even though manually build epScript. The problem related to https://github.com/armoha/euddraft/issues/91. Ok and I struggled to solve this problem and I got it.

# 1. Build epScript
## 1-1. Rename epparser.c to epparser.cpp
https://github.com/armoha/eudplib/blob/c3353eabc2bd431c9004bd3737e8d7a48fcc60dd/src/epscript/CMakeLists.txt#L37-L38 Does not works actually and I don't know why. For now I renamed myself. (FYI: adding echo command does not work. do this line running properly?)
## 1-2. Migrate to catch3
And `make` doesn't work because of `catch.hpp`. So I migrated the `catch.hpp` to `catch_amalgamated.hpp` following this [guide](https://github.com/catchorg/Catch2/blob/devel/docs/migrate-v2-to-v3.md). Maybe it is not fault of catch, maybe version of C++, but I didn't tested.

# 2. Build eudplib
Just do `maturin build`.

# 3. Build euddraft
So I can build euddraft by `setup.py` and still can't use it because there's no `libepScriptLib.dylib` in build result. Import it, and got this.
<img width="617" alt="스크린샷 2024-12-02 오전 10 31 50" src="https://github.com/user-attachments/assets/f0039556-ae90-4843-b092-aea72083fc85">
oh.

**Comment by armoha** [comment]
Both freeze mpqprt and epScript must be built independently. See https://github.com/armoha/euddraft/issues/136

Freeze mpqprt of the current euddraft version is not open sourced due to 'security through obscurity'. This might be changed in future, but for now you need to build freezeMpq.pyd from https://github.com/phu54321/euddraft/tree/master/mpqprt

**Comment by zuhanit** [comment]
I've changed mpqprt code because can't build.

- MemoryCopy to memcpy
- ZeroMemory to memset(dest, 0, len)
- Adding unistd.h in `gzlib.c`, `gzread.c`, `gzwrite.c`

For who want to build this, need to specify architecture like `cmake -DCMAKE_OSX_ARCHITECTURES=arm64 ..`,. if you don't, maybe euddraft stuck on build or can't build.

Anyway, the `applyeuddraft.py` says it need `scbank_core`, whereas it ignored by `.gitignore`. So I removed that code using scbank_core. And provided mpqprt code isn't compatible with therefore removed too. Below is the compile error log, highly solvable, I don't want to struggle with this.

```py
[Error] Population must be a sequence.  For dicts or sets, use sorted(d). Traceback (most recent call last):
  File "/Users/hamjoohan/.local/share/uv/python/cpython-3.11.10-macos-aarch64-none/lib/python3.11/random.py", line 439, in sample
    raise TypeError("Population must be a sequence.  "
TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).
```
 

Finally I got this! 🎉
<img width="617" alt="스크린샷 2024-12-04 오전 5 19 18" src="https://github.com/user-attachments/assets/15ea7a31-d782-4770-b9ee-d87b8188dd3a">

In the game no triggers executed. I don't know why.

**Comment by zuhanit** [comment]
Here's my diff with applyeuddraft.py
```diff
+++ b/applyeuddraft.py
@@ -30,10 +30,7 @@ import warnings
 
 import eudplib as ep
 
-import freezeMpq
 import msgbox
-import scbank_core
-from freeze import decryptOffsets, encryptOffsets, obfpatch, obfunpatch, unFreeze
 from msgbox import MB_ICONHAND, MB_OK, MessageBeep, MessageBox
 from pluginLoader import (
     isFreezeIssued,
@@ -49,12 +46,6 @@ def createPayloadMain(pluginList, pluginFuncDict):
     def payloadMain():
         """Main function of euddraft payload."""
         # init plugins
-        if isFreezeIssued():
-            unFreeze()
-            # ep.PRT_SetInliningRate(0.05)
-
-        if isSCBankIssued():
-            scbank_core.onPluginStart()
 
         for pluginName in pluginList:
             onPluginStart = pluginFuncDict[pluginName][0]
@@ -62,12 +53,6 @@ def createPayloadMain(pluginList, pluginFuncDict):
 
         # Do trigger loop
         if ep.EUDInfLoop()():
-            if isFreezeIssued():
-                decryptOffsets()
-                obfpatch()
-
-            if isSCBankIssued():
-                scbank_core.beforeTriggerExec()
 
             for pluginName in pluginList:
                 beforeTriggerExec = pluginFuncDict[pluginName][1]
@@ -79,12 +64,6 @@ def createPayloadMain(pluginList, pluginFuncDict):
                 afterTriggerExec = pluginFuncDict[pluginName][2]
                 afterTriggerExec()
 
-            if isSCBankIssued():
-                scbank_core.afterTriggerExec()
-
-            if isFreezeIssued():
-                obfunpatch()
-                encryptOffsets()
 
             ep.EUDDoEvents()
 
@@ -238,20 +217,6 @@ def applyEUDDraft(sfname):
             sectorSize = None
         ep.SaveMap(ofname, payloadMain, sector_size=sectorSize)
 
-        if isFreezeIssued():
-            if isPromptIssued():
-                print("Freeze - prompt enabled ")
-                sys.stdout.flush()
-                os.system("pause")
-            print("[Stage 4/3] Applying freeze mpq modification...")
-            try:
-                ofname = ofname.encode("mbcs")
-            except LookupError:
-                ofname = ofname.encode(sys.getfilesystemencoding())
-            ret = freezeMpq.applyFreezeMpqModification(ofname, ofname)
-            if ret != 0:
-                raise RuntimeError("Error on mpq protection (%d)" % ret)
-
         MessageBeep(MB_OK)
         return True
```

Whenever I added epScript code, count of object increased(or decreased). Is there any problems by withdrawing freeze?

**Comment by armoha** [comment]
If I recalled correctly, @phu54321 did build euddraft on macOS using wine.

Anyway both epScript compiler and freeze mpq protection are planned to be rewritten to set up simple CI/CD as #136

**Comment by phu54321** [comment]
안녕하세요~~~

I used euddraft as a native build on macOS, since all the components were released in foss form and all could be compiled. Since my major development went in macOS and users used windows for development, maimtaining cross compatibility was the issue then.

* starcraft were run on wine btw

**Comment by zuhanit** [comment]
안녕하세요~

The map runs flawlessly on Windows. Maybe EUD Emulator can't do its job macOS. Thanks for everyone!
