### ISSUE TITLE
Which block of code should I use?

### ISSUE THREAD

**Issue by Chromowolf** [armoha/euddraft#16]
Say, I were to display some TextFX for every player in the game. 
```js
const s = StringBuffer(1023);
function texteffect() {
    const tecolor = ......;

    const t = s.fadeIn(......) ; 
    ......
}
```
I could come up with several ways to achieve this:
(1)
```js
function afterTriggerExec() {
	foreach(h: EUDLoopPlayer()) {
		setcurpl(h);
		texteffect();
	}
}
```

(2)
```js
function afterTriggerExec() {
	EUDPlayerLoop()();
		texteffect();
	EUDEndPlayerLoop();
}
```

(3)
```js
function afterTriggerExec() {
	const cp = getcurpl(); //just to be safe, prevent desync issue
	setcurpl(getuserplayerid());
	texteffect();
	setcurpl(cp); //just to be safe, prevent desync issue
}
```

Is anyone of them wrong? Are there any major differences in performance?

**Comment by armoha** [comment]
Differences are trivial and negligible.

(1) `EUDLoopPlayer` repeats for active human players. (2) `EUDPlayerLoop` repeats for all active players. There is no iteration or checking if players are active in method (3).
