### ISSUE TITLE
I cann't compile since euddraft 0.9.9.8

### ISSUE THREAD

**Issue by boermyth** [armoha/euddraft#18]
The log:
==============

> Build failed. Please check the log for details.
> [Error] Address should be multiple of 4 Traceback (most recent call last):
>   File "C:\Users\Administrator\Desktop\EUD.Editor2.0.17.9.7b\Data\eudplibdata\TriggerEditor.eps", line 2404, in onPluginStart
>     }
>   File "C:\Py\lib\site-packages\eudplib-0.64.0-py3.8-win32.egg\eudplib\core\rawtrigger\stockact.py", line 408, in SetMemory
>   File "C:\Py\lib\site-packages\eudplib-0.64.0-py3.8-win32.egg\eudplib\utils\eperror.py", line 41, in ep_assert
> eudplib.utils.eperror.EPError: Address should be multiple of 4

===============

Thanks for your good jod, i can use version 0.9.9.0, but i hope i can use the lasest version of euddraft.

**Comment by boermyth** [comment]
EUD.Editor2.0.17.9.7

**Comment by armoha** [comment]
It is intended behavior.
Read error message and fix `TriggerEditor.eps", line 2404, in onPluginStart`.
SetMemory now only accepts memory address of multiple of 4, instead of silently truncating to nearby valid address.
