### ISSUE TITLE
SCA compiling problem

### ISSUE THREAD

**Issue by Chromowolf** [armoha/euddraft#22]
I registered an SCA account, with password having "-" and "@" character. The account was successfully registered, but the password cannot be used in EE3 - SCA settings. 
![scap](https://user-images.githubusercontent.com/37732663/111056388-a4955b80-84b9-11eb-8a41-11d411edb681.png)
I'm sure I've entered the correct battle tag and password. The above picture is just to display the issue. And of course I got compile error:
![QQ图片20210314111141](https://user-images.githubusercontent.com/37732663/111056528-82e8a400-84ba-11eb-8fb7-9a0a80f0821a.png)

I think, either the compiler(or EE3 interpreter?) should support these characters, or SCArchive should not allow these characters appearing in passwords. This inconsistency is a headache for map makers. I'm not sure whether this is EE3's fault or euddraft's fault. Just hope it to be fixed. Could you please help to solve this? thanks

**Comment by armoha** [comment]
I think this is not related to euddraft but SCA registration. You should file this to https://github.com/Buizz/EUD-Editor-3
I've never used SCA but it said incorrect account info. Try recheck input or don't use "-" for now.

**Comment by Chromowolf** [comment]
Then it must be EE3's problem. Already posted an issue for that. Thank you
