### ISSUE TITLE
StringBuffer.printfAt(), {:s} bug: reading 4-byte allignment

### ISSUE THREAD

**Issue by Chromowolf** [armoha/euddraft#26]
The basemap's map name is "abcdef"
Memory 0x6D0F91 stores the map name.
```js
function afterTriggerExec() {
	const cp = getcurpl();
	setcurpl(getuserplayerid());
	const pp = StringBuffer(1024);

	pp.printfAt(0, "Map name, from0 = {:s}", 0x6D0F91); //Expected output: abcdef
	pp.printfAt(1, "Map name, from1 = {:s}", 0x6D0F92); //Expected output: bcdef
	pp.printfAt(2, "Map name, from2 = {:s}", 0x6D0F93); //Expected output: cdef
	pp.printfAt(3, "Map name, from3 = {:s}", 0x6D0F94); //Expected output: def
	pp.printfAt(4, "Map name, from4 = {:s}", 0x6D0F95); //Expected output: ef
	pp.printfAt(5, "0x6D0F90, 0x6D0F94 Hex = {}, {}", hptr(dwread_epd(EPD(0x6D0F90))),hptr(dwread_epd(EPD(0x6D0F94))));
	pp.printfAt(6, "strcmp = {}", strcmp(Db("abcdef"), 0x6D0F91)); //Expected output: 0
	
	setcurpl(cp);
}
```

Test result:
![image](https://user-images.githubusercontent.com/37732663/113147836-c89bbf80-9263-11eb-821a-6147414dba22.png)

Is this intended feature or bug? I'm expecting `{:s}` to read from the specified address, not from the alligned address.

**Comment by armoha** [comment]
It is bug only occur when addstr input is malaligned constant expression.

![image](https://user-images.githubusercontent.com/16814706/113150634-3e595880-926f-11eb-8157-365797082294.png)

```js
function afterTriggerExec() {
    setcurpl(getuserplayerid());
    const name = Db("\0aBcDeFgH") + 1;
    const dbg = StringBuffer(1024);
    var title = name + 2;

    foreach(i : py_range(5)) {
        const i2 = i + i;
        dbg.printfAt(i2, "name[{}..] = {:s}", i, name + i);
        dbg.printfAt(i2 + 1, "title[{}..] = {:s}", i, title + i);
    }
}
```

![image](https://user-images.githubusercontent.com/16814706/113150274-db67c180-926e-11eb-8241-bb9d074f4c37.png)
```js
function afterTriggerExec() {
    setcurpl(getuserplayerid());
    const name = Db("\0aBcDe") + 1;
    const dbg = StringBuffer(1024);
    var title = name;

    for(var i = 0 ; i < 5 ; i += 1) {
        const i2 = i + i;
        dbg.printfAt(i2, "name[{}..] = {:s}", i, name + i);
        dbg.printfAt(i2 + 1, "title[{}..] = {:s}", i, title + i);
    }
}
```

**Comment by armoha** [comment]
Actually it is bug only for formatted print. `dbg.printAt(i2, "name[", i, "..] = ", ptr2s(name + i));` works fine. "s" format *always* converts to "t", `epd2s(EPD(constant))`, missing check if constant is dividable by 4.

**Comment by armoha** [comment]
Fixed in new release 0.9.1.5: https://github.com/armoha/euddraft/releases/tag/v0.9.1.5
Thanks!

**Comment by Chromowolf** [comment]
Cannot compile. Maybe there is some file missing.
![image](https://user-images.githubusercontent.com/37732663/113157515-8c6d5c80-926d-11eb-94d5-dadc17ef0782.png)

![image](https://user-images.githubusercontent.com/37732663/113157634-a6a73a80-926d-11eb-9c09-0c6f542b9318.png)

![image](https://user-images.githubusercontent.com/37732663/113157658-ad35b200-926d-11eb-875c-ad5817ca3968.png)

**Comment by armoha** [comment]
`__pycache__` is generated after compile so it is not related.
I have no problem running 🤔 
![Uploading image.png…]()

**Comment by Chromowolf** [comment]
Weird... I deleted the `__pycache__` and `__epspy__` folders in my project folder, and then it could compile......
thx for the update
