### ISSUE TITLE
[freeze] Error on uncompressed encrypted file

### ISSUE THREAD

**Issue by armoha** [armoha/euddraft#33]
freeze error message:
```
[Stage 4/3] Applying freeze mpq modification...
Cannot get key of non-compressed encrypted block
 - HASHA XXXXXXXX, HASHB XXXXXXXX, BLOCK XXXXXXXX
==========================================
[Error] Error on mpq protection (-2) Traceback (most recent call last):
  File "C:\euddraft\applyeuddraft.py", line 196, in applyEUDDraft
RuntimeError: Error on mpq protection (-2)
```

**Comment by Chromowolf** [comment]
FYI:
This error happens if (listfile) contains non-ASCII character

**Comment by armoha** [comment]
Fixed by following commits (https://github.com/armoha/euddraft/commit/d9c57e5c4af44410b0e9c615999ef928d21be843):
https://github.com/phu54321/euddraft/commit/e5369f3a290205ee52bba0bcba9353892447aae9 https://github.com/phu54321/euddraft/commit/9b55a4f3e7ab3fd942e18860b022861b41ae77b4 

Thank you for your contribution, @phu54321🎉
