### ISSUE TITLE
Padding "0x0D" between concatenated strings

### ISSUE THREAD

**Issue by Chromowolf** [armoha/euddraft#7]
```js
const s = StringBuffer(63);
s.insert(0);
s.append("a", "b");
```
I thought the string should be stored as `61 62 00` at somewhere in the map string section. But when I use Cheat Engine to browse the memory, I see the following:
```
| 61 0D 0D 0D | 62 0D 0D 0D | 00 00 00 00 | 0D 0D 0D 0D .....
```
There are padding "0x0D" in between the concatenated strings to make each substring begins exactly at "EPD" memory address.
Actually I was trying to do the chat detection using `strcmp(s1, s2)`. The above feature makes chat detection even harder. Because `s.appendf("{:n}:\x07content", cp)` will produce a string with unpredictable number of "0x0D"s between the user's name and the colon. 
Why must the 0x0D exist? How may I get around this problem?

**Comment by armoha** [comment]
You don't have to use StringBuffer if you don't need to print it. 0x0D exists for in-game writing performance. StringBuffer methods work in epd unit.

```js
const s = Db(64);
sprintf(s, "ab");
```

**Comment by Chromowolf** [comment]
Brilliant! It works.
May I ask which 2 words "Db" stands for?

**Comment by armoha** [comment]
Ask @phu54321 . I didn't coin it ;p
Maybe dump byte or something, not sure.

**Comment by Chromowolf** [comment]
OK thank you

**Comment by phu54321** [comment]
'DB' means 'dump byte'. The name originates from x86 assembly language.
The following example code is from https://en.wikipedia.org/wiki/X86_assembly_language#Examples

```
.model small
.stack 100h

.data
msg	db	'Hello world!$'

.code
start:
	mov	ah, 09h   ; Display the message
	lea	dx, msg
	int	21h
	mov	ax, 4C00h  ; Terminate the executable
	int	21h

end start
```
