### ISSUE TITLE
f_strlen() bug?

### ISSUE THREAD

**Issue by Chromowolf** [armoha/euddraft#8]
```js
eprintf("{}, {}, {}, {}", strlen(Db("123")), strlen(Db("1234")), 
        strlen(Db("12345")), strlen(Db("123456")));
```
I got 0,0,1,2 instead of 3,4,5,6
Is that a bug?

**Comment by armoha** [comment]
Fixed at next version. It was bug when address is multiples of 4.

But for performance point of view, if you know the address is multiples of 4, use f_strlen_epd for better performance.
